# Generated by Django 4.2.1 on 2023-05-27 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('stock', models.DecimalField(decimal_places=0, default=1, max_digits=3)),
                ('image', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=0, default=1, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=300)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
